# Basic
title: One Wang
subtitle: 优胜劣汰
welcome_message: 生命不息，奋斗不止。
description: 努力……
creator: <a href="https://github.com/OneWang">@onewang</a>

url: "https://github.com/OneWang"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: ''}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: jack
    # duoshuo: 
    
# Social
social:
    weibo: onewang
    github: onewang
    twitter: 
    gplus: 107108267983477358170
    mail: jackwangqingfei@gamail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
